k_values:
  - 31

random_seed: 1

matrices:
  kmer: true
  unitig: true
  uniqrow: true

outputs:
  best_tsp: true
  worst_tsp: true
  nj_attotree: true
  upgma_attotree: true
  randomized: true

attotree_k: 31
attotree_s: 10000
