#!/usr/bin/env bash
set -euo pipefail
export LD_PRELOAD=/mnt/lustre/helios-home/hendrver/miniconda3/envs/ism/lib/libstdc++.so.6.0.34

ulimit -n 4096
snakemake -j 32 --resources concurrency=1 --latency-wait 30 --rerun-incomplete --keep-going --show-failed-logs --use-conda
